import BuyBtn from '@/components/general/BuyBtn'
import Title from '@/components/general/Title'
import Layout from '@/components/layout /Layout'
import SingleProduct from '@/components/products/SingleProduct'
import { supabase } from '@/lib/supabase'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'

export default function Home() {
  const [products, setProducts] = useState([])
  const fetcher = async() => {
    const {data, error} = await supabase.from('products').select().eq('featured', true)
    if(error) console.log(error)
    setProducts(data)
  }

  useEffect(() => {
    fetcher()
  }, [])
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='py-12 '>
      <Title text="Featured Products" />
      <main className="flex flex-wrap gap-2 justify-center container mx-auto">
        {products.map(item => {
          return (
            <Link key={item.id} href={`products/${item.id}`}>
              <SingleProduct item={item} />
            </Link>
          )
        })}
      </main>
      </div>
    </Layout>
  )
}
